class SpellClass:
    def __init__(self, cn, _range, target, duration, description):
        self.cn = cn    # str
        self._range = _range   # str
        self.target = target  # str
        self.duration = duration  # str
        self.description = description  # str


spells_petty = {
    'Animal Friend':    SpellClass('0', '1 yard', '1', '1 hour', f'You make friends with a creature that is smaller than you and possesses the Bestial Creature Trait. The animal trusts you completely and regards you as a friend.'),
    'Bearings':         SpellClass('0', 'You', 'You', 'Instant', f'You sense the influx of the Winds of Magic from their source. You know which direction North is.'),
    'Dazzle':           SpellClass('0', 'Touch', '1', '[bWP] round(s)', f'The target gains 1 Blinded Condition, and gains 1 Blinded Condition at the start of each round for the duration of the spell.'),
    'Careful Step':     SpellClass('0', 'You', 'You', '[WP] minute(s)', f'The magic flowing through your feet ensures any organic matter you tread upon remains undamaged: twigs do not break, grass springs back to its original position, and even delicate flowers are unharmed. Those seeking to use the Track skill to pursue you through rural terrain suffer a –30 penalty to their Tests.'),
    'Conserve':         SpellClass('0', '1 yard', '1', '[WP] day(s)', f'You preserve up to a day’s worth of rations. During this time they will not rot, develop mould, or go stale, although they can still be harmed by external factors, such as getting wet or being burned or poisoned.'),
    'Dart':             SpellClass('0', '[WP] yard(s)', '1', 'Instant', f'You cause a small dart of magical energy to fly from your fingers. This is a magic missile with a Damage of +0.'),
    'Drain':            SpellClass('0', 'Touch', '1', 'Instant', f'You touch your targets, draining their life. This counts as a magic missile with Damage +0 that ignores Armour Points. You then Heal 1 Wound.'),
    'Eavesdrop':        SpellClass('0', '[WP] yard(s)', '1', '[bI] minute(s)', f'You can hear what your targets say as if you were standing right next to them.'),
    'Gust':             SpellClass('0', '[WP] yard(s)', 'Special', 'Instant', f'You create a brief gust of wind, strong enough to blow out a candle, cause an open door to slam, or blow a few pages to the floor.'),
    'Light':            SpellClass('0', 'You', 'You', '[WP] minute(s)', f'You create a small light, roughly equivalent to a torch, which glows from your hand, staff or some other part of your person. While the spell is active, you may choose to increase the illumination to that of a lantern, or decrease it to that of a candle, if you pass a Average (+20) Channelling Test.'),
    'Magic Flame':      SpellClass('0', 'You', 'You', '[bWP] round(s)', f'You kindle a small flame that flickers to life in the palm of your hand. It will not burn you, but will emit heat and set flammable objects alight, like a natural flame.'),
    'Marsh Lights':     SpellClass('0', '[WP] yard(s)', 'Special', '[WP] minute(s)', f'You create [bINT] flickering magical lights. They resemble torches or hooded lanterns. Providing they remain within line of sight, for your Action you may control the lights by passing a Average (+20) Channelling Test; a success allows you to send the lights moving in any direction. They will move at walking pace in a straight line, passing through any objects (or witnesses) in their path, unless you test again to change their direction.'),
    'Murmured Whisper': SpellClass('0', '[WP] yard(s)', 'Special', '[bWP] round(s)', f'You cast your voice at a point within Willpower yards, regardless of line of sight. Your voice sounds from this point, and all within earshot will hear it.'),
    'Open Lock':        SpellClass('0', 'Touch', 'Special', 'Instant', f'One non-magical lock you touch, opens.'),
    'Produce Small Animal': SpellClass('0', 'Touch', 'Special', 'Instant', f'You reach into a bag, pocket, or hat, or under a rock, bush or burrow, producing a small animal of a type you would expect to find in the vicinity, such as a rabbit, dove, or rat. If there are no appropriate local animals, the spell does nothing. The temperament of the animal is not guaranteed.'),
    'Protection from Rain': SpellClass('0', 'You', 'You', '[bT] hour(s)', f'You can keep yourself dry whatever the weather, unaffected by precipitation. This affects rain, hail, sleet and snow, and any similar water falling from the heavens, but not standing water.'),
    'Purify Water':     SpellClass('0', '1 yard', 'Special', 'Instant', f'You purify all water within a receptacle, such as a water flask, stein, or jug. All non-magical impurities, such as poison or contaminants are removed, leaving crisp, clear, potable water. If the vessel contained another liquid that is predominantly water – such as ale, or wine – this is also purified, turning into delicious, pure, non-alcoholic water.'),
    'Rot':              SpellClass('0', '1 yard', 'Special', 'Instant', f'You cause a roughly fist-sized volume of organic material to immediately rot. Food stuffs perish, clothes crumble, leathers shrivel (losing 1 Armour Point on 1 hit location), and similar, as dictated by the GM.'),
    'Sleep':            SpellClass('0', 'Touch', '1', '[bWP] round(s)', f'You touch your opponent, sending them into a deep sleep. If the target has the Prone Condition, they gain the Unconscious Condition as they fall asleep. They remain unconscious for the duration, although loud noises or being moved or jostled will awaken them instantly. If your targets are standing or sitting when affected, they start themselves awake as they hit the ground, gaining the Prone Condition, but remaining conscious. If your targets are not resisting, and are suitably tired, they will, at the spell’s end, pass into a deep and restful sleep.'),
    'Spring':           SpellClass('0', 'Touch', 'Special', '[bWP] round(s)', f'You touch the ground and water bubbles forth at the rate of [bI] pint(s) per Round.'),
    'Shock':            SpellClass('0', 'Touch', '1', 'Instant', f'Your target receives 1 Stunned Condition.'),
    'Sly Hands':        SpellClass('0', 'You', 'You', '[bWP] round(s)', f'You teleport a small object — no bigger than your fist — from about your person into your hand.'),
    'Sounds':           SpellClass('0', '[WP] yard(s)', 'Special', '[bWP] round(s)', f'You create small noises nearby. You can create quiet, indistinct noises that sound as if they come from a specific location within range, regardless of line of sight. The noises can evoke something specific, such as footsteps, whispers or the howl of an animal, but nothing so distinct that it might convey a message. While the spell is active, you may control the sounds by passing a Average (+20) Channelling Test. A success allows you to move the sounds to another point within range, or to increase or decrease their volume.'),
    'Twitch':           SpellClass('0', '[bWP] yard(s)', 'Special', 'Instant', f'You cause a small object to move, slightly. Something may fall from a shelf, or a book may slam its pages shut. If the object is held, the holder must pass an Average (+20) Dexterity Test or drop the object.'),
    'Warning':          SpellClass('0', '1 yard', 'Special', 'Instant', f'You channel magic into an object, noticing immediately if it has been poisoned or trapped.')
}


spells_arcane = {
    'Aethyric Armour':  SpellClass('2', 'You', 'You', '[bWP] round(s)+', f'You gain +1 Armour Point to all Hit Locations as you wrap yourself in a protective swathe of magic. When the spell should end, you may make a Willpower Test to extend the Duration for +1 round.'),
    'Aethyric Arms':    SpellClass('2', 'You', 'You', '[bWP] round(s)+', f'You create a weapon with a Damage equal to your [bWP]. This may take any form, and so use any Melee Skill you may possess. The weapon counts as Magical. When the spell should end, you may make a Willpower Test to extend the Duration for +1 round.'),
    'Arrow Shield':     SpellClass('3', 'You', 'AoE ([bWP] yard(s))', '[bWP] round(s)+', f'Any missiles containing organic matter, such as arrows with wooden shafts, are automatically destroyed if they pass within the Area of Effect, causing no damage to their target. Missiles comprising only inorganic matter, such as throwing knives or pistol shots, are unaffected. When the spell should end, you may make a Willpower Test to extend the Duration for +1 round.'),
    'Blast':            SpellClass('4', '[WP] yard(s)', 'AoE ([bWP] yard(s))', 'Instant', f'You channel magic into an explosive blast. This is a magic missile with Damage +3 that targets everyone in the Area of Effect.'),
    'Bolt':             SpellClass('4', '[WP] yard(s)', '1', 'Instant', f'You channel magic into a damaging bolt. Bolt is a magic missile with a Damage of +4.'),
    'Breath':           SpellClass('6', '1 yard', 'Special', 'Instant', f'You immediately make a Breath attack, as if you had spent 2 Advantage to activate the Breath Creature Trait (see page 338). Breath is a magic missile with a Damage equal to your [bT]. The GM decides which type of Breath attack best suits your Arcane Magic Talent.'),
    'Bridge':           SpellClass('4', '[WP] yard(s)', 'AoE', '[bWP] round(s)+', f'You create a bridge of magical energy, with a maximum length and breadth of your [bWP] in yards. For every +2 SL you may increase length or breadth by your [bWP] in yards. When the spell should end, you may make a Willpower Test to extend the Duration for +1 round.'),
    'Chain Attack':     SpellClass('6', '[WP] yard(s)', 'Special', 'Instant', f'You channel a twisting spur of rupturing magic into your target. This is a magic missile with a Damage of +4. If Chain Attack reduces a target to 0 Wounds, it leaps to another target within the spell’s initial range, and within [bWP] yards of the previous target, inflicting the same Damage again. It may leap a maximum number of times equal to your [bWP]. For every +2 SL achieved, it may chain to an additional target.'),
    'Corrosive Blood':  SpellClass('4', 'You', 'You', '[bWP] round(s)', f'You infuse yourself with magic, lending your blood a fearsome potency. You gain the Corrosive Blood Creature Trait (see page 339).'),
    'Dark Vision':      SpellClass('1', 'You', 'You', '[bWP] round(s)', f'You boost your Second Sight to assist your mundane senses. While the spell is active, gain the Dark Vision Creature Trait (see page 339).'),
    'Distracting':      SpellClass('4', 'You', 'You', '[bWP] round(s)', f'You wreathe yourself in magic, which swirls around you, distracting your foes. While the spell is active, gain the Distracting Creature Trait (see page 339).'),
    'Dome':             SpellClass('7', 'You', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'You create a dome of magical energy overhead, blocking incoming attacks. Anyone within the Area of Effect gains the Ward (6+) Creature Trait (see page 343) against magical or ranged attacks originating outside the dome. Those within may attack out of the dome as normal, and the dome does not impede movement.'),
    'Drop':             SpellClass('1', '[WP] yard(s)', '1', 'Instant', f'You channel magic into an object being held by an opponent. This could be a weapon, a rope, or someone’s hand. Unless a Challenging (+0) Dexterity Test is passed, the item is dropped. For every +2 SL you may impose an additional –10 on the Dexterity Test.'),
    'Entangle':         SpellClass('3', '[WP] yard(s)', '1', 'Special', f'Using magic, you entrap your target, wrapping them in whatever suits your Lore: vines, shadows, their own clothing… Your target gains one Entangled Condition with a Strength equal to your Intelligence. For every +2 SL, you may give the target +1 additional Entangled Condition. The spell lasts until all Entangled Conditions are removed.'),
    'Fearsome':         SpellClass('3', 'You', 'You', '[bWP] round(s)', f'Shrouding yourself in magic, you become fearsome and intimidating. Gain Fear 1. For every +3 SL, you may increase your Fear value by one.'),
    'Flight':           SpellClass('8', 'You', 'You', '[bWP] round(s)+', f'You can fly, whether by sprouting wings, ascending on a pillar of magical light, or some other method. Gain the Flight (Agility) Creature Trait (see page 339). When the spell should end, you may make a Willpower Test to extend the Duration for +1 round.'),
    'Magic Shield':     SpellClass('4', 'You', 'You', '[bWP] round(s)', f'You encase yourself in bands of protective magic. While the spell is active, add +[bWP] SL to any dispel attempts you make.'),
    'Move Object':      SpellClass('4', '[WP] yard(s)', '1', '1 round', f'Using magic, you grab hold of an non-sentient object no larger than you, moving it with the sheer force of your will, which is considered to have a Strength equal to your Willpower. You may move the object up to [bWP] yard(s). If anyone attempts to impede the object’s movement, make a Contested Willpower/Strength Test. For every +2 SL you may increase the distance the object is moved by [bWP] yard(s).'),
    'Mundane Aura':     SpellClass('4', 'You', 'You', '[WP] minute(s)', f'You drain all the Winds of Magic from within your body and your possessions, removing any magical aura. For the duration of the spell you appear mundane to the Magical Sense Talent and similar. You effectively have no magical ability and your magical nature cannot be detected by any means. While this spell is in effect, you cannot cast any other spells. Mundane Aura is immediately dispelled if you make a Channelling Test.'),
    'Push':             SpellClass('6', 'You', 'You', 'Instant', f'All living creatures within [bWP] yard(s) are pushed back for [bWP] yard(s) and gain the Prone Condition. If this brings them into contact with a wall or other large obstacle, they take Damage equal to the distance travelled in yards. For every +2 SL, you may push creatures back for another [bWP] yard(s).'),
    'Teleport':         SpellClass('5', 'You', 'You', 'Instant', f'Using magic, you can teleport up to [bWP] yard(s). This movement allows you to traverse gaps, avoid perils and pitfalls, and ignore obstacles. For every +2 SL you may increase the distance travelled by [bWP] yard(s).'),
    'Terrifying':       SpellClass('7', 'You', 'You', '[bWP] round(s)', f'You gain the Terror (1) Creature Trait (see page 191).'),
    'Ward':             SpellClass('5', 'You', 'You', '[bWP] round(s)', f'You wrap yourself in protective magic, gaining the Ward (9+) Creature Trait (see page 343).')
}


spells_lore_beasts = {
    'Amber Talons':     SpellClass('6', 'You', 'You', '[bWP] round(s)', f'Your nails grow into wickedly sharp talons of crystal amber. Unarmed attacks made using Melee (Brawling) count as magical, have a Damage equal to your [bWP], and inflict +1 Bleeding Condition whenever they cause a loss of Wounds.'),
    'Beast Form':       SpellClass('5', 'You', 'You', '[WP] minutes', f'You infuse your very bones and flesh with Ghur, warping your body into that of a creature. When cast, select a new form from any of the Beasts of the Reikland section of the Bestiary (see page 314). Use the standard Traits for the creature. For every + 2 SL, you may include 1 of the included Optional Creature Trait. While in Beast Form, you look like a normal version of the creature, with amber and brown colouring. You may not speak, which means you cannot cast spells, or attempt to dispel.'),
    'Beast Master':     SpellClass('10', '[bWP] yard(s)', '1', '[bWP] days', f'Your breath steams and your eyes take on a shining amber sheen as Ghur suffuses you. Your gaze and words convince 1 creature possessing the Bestial trait that you are its pack master, and it will fight to the death to protect you. While subject to your mastery it will follow your instructions, instinctively understanding simple instructions. If the creature is released from the spell — through the duration running out, or the spell being dispelled — it will retain enough residual respect and fear not to attack you, unless compelled to. Your allies may not be so fortunate.'),
    'Beast Tongue':     SpellClass('3', 'You', 'You', '[WP] minutes', f'You can commune with all creatures possessing the Bestial Trait. Ghur clogs your throat, and your language comes out as snarls, hisses, and roars as befits the beasts to whom you talk. While the creatures are not compelled to answer you, or do as you bid, most will be curious enough to hear you out. You gain +20 on all Charm Animal and Animal Training Tests While this spell is active, you may only speak with beasts — you may not speak any civilised tongues, and can only communicate with your party using gestures or Language (Battle). Note, this also means you cannot cast any spells, or dispel, while Beast Tongue is active.'),
    'Flock of Doom':    SpellClass('8', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'You call down a murder of crows or similar local bird to assail your foes. The flock attacks everyone in the Area of Effect who does not possess the Arcane Magic (Beasts) Talent ferociously, inflicting a +7 Damage hit at the end of the round. The flock remains in play for the duration of the spell. For your Action you may make an Average (+20) Charm Animal Test to move the flock to another target within range. While within the Area of Effect, all creatures gain +1 Blinded Condition.'),
    'Hunter’s Hide':    SpellClass('6', 'You', 'You', '[bWP] round(s)', f'You cloak yourself in a shimmering mantle of Ghur. While the spell lasts, gain a bonus of +20 Toughness and the Dark Vision and Fear (1) Creature Traits (see page 339), as well as the Acute Sense (Smell) Talent.'),
    'The Amber Spear':  SpellClass('8', '[WP] yard(s)', 'Special', 'Instant', f'You hurl a great spear of pure Ghur in a straight line. This is a magic missile with a Damage of +12. It strikes the first creature in its path, ignoring APs from armour made of leather and furs. If the target suffers any Wounds, also inflict +1 Bleeding Condition, after which the spear continues on its path, striking each target in the same manner, but at –1 Damage each time. If the spear fails to inflict any Wounds, its progress is stopped and the spell comes to an end. The Amber Spear only inflicts the minimum 1 Wound (see page 236) on the first target it strikes.'),
    'Wyssan’s Wildform':SpellClass('8', 'You', 'You', '[bWP] round(s)', f'You call on the wild power of Ghur to infuse you, surrendering to its savage delights. Gain the following Creature Traits (see page 338): Arboreal, Armour (2), Belligerent, Big, Bite ([bS+1]), Fear (1), Fury, Magical, Weapon ([bS+2]). While the spell is in place you are incapable of using any Language or Lore skills.')
}


spells_lore_death = {
    'Caress of Laniph': SpellClass('7', 'Touch', 'Special', 'Instant', f'As you reach out your hand, it appears withered, even skeletal, drawing Shyish from your target’s corpus. This counts as a magic missile with a Damage of +6 that ignores Toughness Bonus and Armour Points. For every 2 Wounds inflicted, you may recover 1 Wound.'),
    'Dying Words':      SpellClass('6', 'Touch', '1', '[bWP] round(s)', f'Touching the body of a recently departed soul (one that passed away within the last day), you call its soul back briefly. For the spell’s duration, you can communicate with the dead soul, though it cannot take any action other than talking. It is not compelled to answer you, but the dead do not lie.'),
    'Purple Pall of Shyish': SpellClass('9', 'You', 'You', '[bWP] round(s)', f'You pull about you a pall fashioned from fine strands of purple magic. Gain +[bWP] Armour Points on all locations, and the Fear (1) Creature Trait (see page 339). For every +2 SL you may increase your Fear rating by 1.'),
    'Sanctify':         SpellClass('10', 'Touch', 'AoE ([bWP] yard(s))', '[WP] minute(s)', f'Inscribing a magical circle, you ward it with Shyish, forming an impenetrable barrier to the Undead. Creatures with the Undead Creature Trait cannot enter or leave the circle.'),
    'Scythe of Shyish': SpellClass('6', 'You', 'You', '[bWP] round(s)', f'You conjure a magical scythe, which can be wielded in combat, using the Melee (Polearm) Skill. It acts like a normal scythe with a Damage equal to your [bWP+3]. Enemies with the Undead Creature Trait do not receive Advantage when Engaged in combat with you.'),
    'Soul Vortex':      SpellClass('8', '[WP] yard(s)', 'AoE ([bWP] yard(s))', 'Instant', f'You hurl a shimmering ball of Shyish which erupts into purple flames, swirling with ghostly faces, mouths agape in silent terror. Targets within the Area of Effect receive +1 Broken Condition. Against targets with the Undead Creature Trait, Soul Vortex is a magic missile with a Damage of +10 that ignores Toughness Bonus and Armour Points.'),
    'Steal Life':       SpellClass('7', '[WP] yard(s)', '1', 'Instant', f'Thin strands of purple mist connect you briefly to your target, who wastes away before your very eyes. This counts as a magic missile with a Damage of +6 that ignores Armour Points and inflicts +1 Fatigued Condition. Further, you remove all Fatigued Conditions you currently suffer, and may heal yourself up to half the Wounds the target suffers, rounding up.'),
    'Swift Passing':    SpellClass('6', 'Touch', 'Special', 'Instant', f'Your touch brings the release of death to a single mortally wounded target. If you successfully touch a target with 0 wounds remaining and at least 2 Critical Wounds, death swiftly follows. Further, the target cannot be raised as Undead.')
}


spells_lore_fire = {
    'Aqshy’s Aegis':    SpellClass('5', 'You', 'You', '[bWP] round(s)', f'You wrap yourself in a fiery cloak of Aqshy, which channels flame into the Aegis. You are completely immune to damage from non-magical fire, including the breath attacks of monsters, and ignore any Ablaze Conditions you receive. You receive the Ward (9+) Creature Trait (see page 343) against magical fire attacks including spells from the Lore of Fire.'),
    'Cauterise':        SpellClass('4', 'Touch', '1', 'Instant', f'Channelling Aqshy through your hands you lay them on an ally’s wounds. Immediately heal 1d10 Wounds and remove all Bleeding Conditions. Further, the wounds will not become infected. Targets without the Arcane Magic (Fire) Talent, must pass a Challenging (+0) Cool Test or scream in agony.. If Failed by –6 or more SL, the target gains the Unconscious Condition and is permanently scarred, waking up 1d10 hours later'),
    'Crown of Flame':   SpellClass('8', 'You', 'You', '[bWP] round(s)', f'You channel Aqshy into a majestic crown of inspiring fire about your brow. Gain the Fear (1) Trait and +1 War Leader Talent while the spell is active. For every +2 SL, you may increase your Fear value by +1, or take War Leader Talent again. Furthermore, gain a bonus of +10 on all attempts to Channel and Cast with Aqshy while the spell is in effect.'),
    'Flaming Hearts':   SpellClass('8', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'Your voice takes on a rich resonance, echoing with Aqshy’s fiery passion. Affected allies lose all Broken and Fatigued Conditions, and gain +1 Drilled, Fearless and Stout-hearted Talent while the spell is in effect.'),
    'Firewall':         SpellClass('8', '[WP] yard(s)', 'Aoe(Special)', '[bWP] round(s)', f'You channel a fiery streak of Aqshy , creating a wall of flame. The Firewall is [bWP] yard(s) wide, and 1 yard deep. For every +2 SL you may extend the length of the Firewall by +[bWP] yard(s). Anyone crossing the firewall gains 1 Ablaze condition and suffers a hit with a Damage=[bWP], handled like a magical missile .'),
    'Great Fires of U’Zhul': SpellClass('10', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'You hurl a great, explosive blast of Aqshy into an enemy, which erupts into a furious blaze, burning with the heat of a forge. This is a magical missile with Damage +10 that ignores Armour Points and inflicts +2 Ablaze Conditions and the Prone Condition on a target. Everyone within the Area of Effect of that target suffers a Damage +5 hit ignoring Armour Points, and must pass a Dodge Test or also gain +1 Ablaze Condition. The spell stops behaving like a magic missile as the fire continues to burn in the Area of Effect for the duration. Anyone within the Area of Effect at the start of a round suffers 1d10+6 Damage, ignoring APs, and gains +1 Ablaze Condition.'),
    'Flaming Sword of Rhuin':SpellClass('8', '[WP] yard(s)', '1', '[bWP] round(s)', f'You wreathe a sword in magical flames. The weapon has Damage +6 and the Impact Quality (see page 298), and anyone struck by the blade gains +1 Ablaze Condition. If wielders do not possess the Arcane Magic (Bright) Talent, and they fumble an attack with the Flaming Sword, they gain +1 Ablaze Condition.'),
    'Purge':            SpellClass('10', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'You funnel intense flame to burn away the taint and corruption in an area. Anything flammable is set alight, and any creatures in the area takes +SL Ablaze conditions. If the location contains a Corrupting Influence, such as Dhar , warpstone, or a Chaostainted object, it too will smoulder and blacken, beginning to burn. This spell may be maintained in subsequent rounds by passing a Challenging (+0) Channelling Test. The precise time needed to eliminate the Corrupting Influence will be determined by your GM. As a rough guideline, a small quantity (smaller than an acorn) of warpstone, or a minor Chaos-tainted object may require 10–[bWP] round(s) (minimum of 1 Round). A larger quantity of warpstone — fist-sized — or a more potent Chaos-tainted object may require double this. A powerful Chaos Artefact may take hours, or even longer… See page 182 for detail on Corrupting Influences.')
}


spells_lore_heavens = {
    'Cerulean Shield':      SpellClass('7', 'You', 'You', '[bWP] round(s)', f'You encase yourself in a crackling cage of sparking electricity and Azyr . For the spell’s duration, gain +SL Armour Points to all locations against melee attacks. If attacked by metal weapons — such as daggers, swords, and spears with metal tips — your attacker takes +Willpower Bonus Damage.'),
    'Comet of Casandora':   SpellClass('10', '[I] yard(s)', 'AoE ([bI] yard(s))', 'Special', f'You channel all the Azyr you can muster and reach out to the skies, calling down a comet to wreak havoc amongst your foes. Select a target point within range. At the end of the next round, make an Average (+0) Perception Test. For every +SL you achieve, you may move your point of impact by [bI] yard(s). For every –SL, the GM will move the point of impact by [bI] yards in a random direction. Comet of Casandora then acts as a magical missile with Damage +12 that hits all targets in the Area of Effect, who also gain +1 Ablaze and the Prone Condition.'),
    'Fate’s Fickle Fingers':SpellClass('6', 'You', 'AoE ([bI] yard(s))', '[bWP] round(s)', f'All allies within the Area of Effect, excluding those with the Arcane Magic (Heavens) Talent, create a single pool for their Fortune Points. All may draw on the pool, first come, first served. When the spell ends, you reallocate any remaining Fortune Points as fairly as possible.'),
    'Starcrossed':          SpellClass('7', '[WP] yard(s)', '1', '[bI] round(s)', f'While this spell is active, you can spend Fortune Points to force an opponent to reroll Tests.'),
    'T’Essla’s Arc':        SpellClass('7', '[WP] yard(s)', '1', 'Instant', f'A crackling bolt of lightning shoots from your fingertips, striking your target. This is a magic missile with Damage +10 that inflicts +1 Blinded condition.'),
    'The First Portent of Amul': SpellClass('3', 'You', 'You', '[bI] round(s)', f'Gain +1 Fortune Point. For every +2 SL, gain +1 more. Any of these points unused at the end of the Duration are lost.'),
    'The Second Portent of Amul': SpellClass('6', 'You', 'You', '[bI] round(s)', f'Gain +SL Fortune Points. For every +2 SL, gain +1 additional Fortune point. Any unused points at the end of the Duration are lost.'),
    'The Third Portent of Amul': SpellClass('12', 'You', 'You', '[bI] round(s)', f'Gain +1 Fate Point. If the Fate point is not used by the end of the Duration, it is lost.')
}


spells_lore_metal = {
    'Crucible of Chamon':   SpellClass('7', '[bWP] yard(s)', '1', 'Instant', f'You channel Chamon into a single non-magical, metallic object, such as a weapon or piece of armour. The item melts, dripping to the floor as molten metal, cooling almost immediately. If held, the item is dropped. If worn, the wearer takes a hit like a magic missile with Damage equal to your Willpower Bonus that ignores Toughness Bonus. While the object is destroyed, the metal retains its base value, and may be used by a smith as raw material.'),
    'Enchant Weapon':       SpellClass('6', 'Touch', 'Special', '[bWP] round(s)', f'You encase a single non-magical weapon with heavy bands of Chamon, enhancing its potency. For the duration of the spell it counts as magical, gains a bonus to Damage equal to your Willpower Bonus, and gains the Unbreakable Quality (see page 298). For every +3 SL you may also add 1 Quality or remove 1 Flaw from the weapon, while the spell is in effect.'),
    'Feather of Lead':      SpellClass('5', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'Calling on the golden wind, you alter the density of your target’s belongings, raising or lowering their weight. For the duration of the spell, choose one effect for everyone within the area of effect: • Count as Encumbered • Do not count as Encumbered See page 293 for details on Encumbrance.'),
    'Fool’s Gold':          SpellClass('4', 'Touch', '1', '[WP] minute(s)', f'You weave Chamon into a non-magical object made of metal, fundamentally altering its alchemical nature. For the duration of the spell, all metal in the object becomes gold. This is not an illusion: it has actually transformed into gold. When the spell ends, the item reverts to its original metal. This spell can ruin good weapons, make armour too heavy to wear, and turn lead coins into something much more appealing. Spot effects arising from this spell are left in the hands of the GM.'),
    'Forge of Chamon':      SpellClass('9', '[bWP] yard(s)', 'Special', '[WP] minute(s)', f'You alter the quality of a single item made of metal. You may add 1 Quality or remove 1 Flaw. For every +2 SL, you may add another Quality or remove another Flaw.'),
    'Glittering Robe':      SpellClass('5', 'You', 'You', '[bT] round(s)', f'Wild flurries of Chamon whirl around you, deflecting blows and intercepting missiles and magical attacks. Gain the Ward(9+) Creature Trait (see page 343) against all attacks and spells targeting you. Each hit successfully saved increases the Ward’s effectiveness by 1, to a maximum of Ward (3+).'),
    'Mutable Metal':        SpellClass('5', 'Touch', '1', '[bWP] round(s)', f'You touch a non-magical object made of metal, which instantly becomes warm to the touch as you squeeze Chamon into it. You may bend and mangle the object with an Average (+20) Strength Test. If you wish to make a more complex alteration, you may attempt an Average (+20) Trade (Smith, or similar) Test instead.'),
    'Transmutation of Chamon': SpellClass('12', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'You wrench Chamon from the metals worn by your foes, and the earth itself, briefly transforming the flesh of your enemies into metal. This is a magic missile affecting all in the Area of Effect, with a Damage equal to your Willpower Bonus; the spell ignores Toughness Bonus and inflicts +1 Blinded, Deafened, and Stunned Condition, all of which last for the duration of the spell. All affected targets gain +1 Armour Point from the gold wrapped about their bodies, but also suffer from Suffocation (see page 181). If targets die while the spell is in effect, they are permanently encased in a shell of base metals, a macabre reminder of the risks of sorcery.')
}


spells_lore_life = {
    'Barkskin':         SpellClass('3', 'Touch', '1', '[bWP] round(s)', f'You cause the target’s skin to become hard and rough like the bark of a tree. While affected by the spell, add +2 to the target’s Toughness Bonus, but suffer a penalty of –10 to Agility and Dexterity.'),
    'Earthblood':       SpellClass('6', 'You', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'To cast this spell, you must be in direct contact with the earth. Standing barefoot counts. For the duration of the spell, any creatures in direct contact with the earth within AoE heal Wounds equal to your Willpower Bonus at the start of every Round.'),
    'Earthpool':        SpellClass('8', 'You', 'You', 'Instant', f'On casting the spell, you immediately disappear into the ground in a wild torrent of Ghyran . You appear at the start of the next Round at any point within your Willpower in yards, erupting from the earth violently. For every +2 SL you may increase the distance travelled by your Willpower in yards. Any enemies engaged by you on your appearance gain the Surprised Condition. This spell will not allow you to move through stone but will allow you to move through water.'),
    'Fat of the Land':  SpellClass('4', 'Touch', '1', '[bWP] day(s)', f'You flood the target’s body with nourishing Ghyran . The target need not eat or drink, but will still excrete as normal, though any leavings will be verdant green.'),
    'Forest of Thorns': SpellClass('6', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'This spell may only target a patch of earth (though the patch can be very small). You cause a dense knot of wickedly spiked brambles and tangled vines to burst upwards, covering the Area of Effect. While the spell is active, anyone attempting to traverse the area on foot without the Arcane Magic (Life) Talent must make a Hard (–20) Agility Test. Failure means they gain 1 Bleeding Condition, and 1 Entangled Condition, with your Willpower used for its Strength. After the spell concludes, the growth remains, but loses its preternatural properties.'),
    'Lie of the Land':  SpellClass('5', '[bI] mile(s)', 'You', 'Special', f'Touching the earth, your senses flow through the Ghyran tracing the nearby area. After communing for 1 minute, you receive a detailed mental map of all-natural features — land, forests, rivers, but not settlements — within range. Settlements may be alluded to — areas of clear terrain, or dug trenches, for example. Each time you increase the range with SL increases the time taken communing with the land by +1 minute.'),
    'Lifebloom':        SpellClass('8', '[bWP] yard(s)', 'Special', 'Special', f'You cause Ghyran to flood an area that is blighted or desolate. You may target either a dry riverbed, well, field, or a domestic animal. If you successfully cast the spell, the target bursts to life: • A dry river begins to flow once again • A dry or polluted well becomes clean and fresh • A planted field, vineyard or orchard bursts into life, with all crops immediately reaching full ripeness • A sick or unproductive animal becomes healthy. The affected beast is now healthily productive (cows produce milk, hens lay eggs, coats and hides of sheep and cows are healthy and lustrous) and any diseases are cured.'),
    'Regenerate':       SpellClass('6', 'Touch', '1', '[bWP] round(s)', f'Your target gains the Regenerate Creature Trait (see page 341).')
}


spells_lore_light = {
    'Banishment':       SpellClass('12', 'You', 'AoE ([bWP] yard(s))', 'Instant', f'You send a cleansing halo of Hysh out from hands, affecting all creatures within the Area of Effect whose Toughness is lower than your Willpower. Targets with the Undead and Daemonic Creature Traits gain the Unstable Creature Trait (see page 343). If they already have the Unstable Trait, they are reduced to 0 Wounds.'),
    'Blinding Light':   SpellClass('5', '[WP] yard(s)', 'You', 'Instant', f'You emit a bright, blinding flash of light from your hand or staff. Everyone looking at you, unless they possess the Arcane Magic (Light) Talent, receives +SL Blinded Conditions.'),
    'Clarity of Thought': SpellClass('6', 'Touch', '1', '[INT] minute(s)', f'You calm your target’s mind, allowing them to think clearly. All negative modifiers on their thinking processes — from Conditions, Mental Mutations, Psychologies, or any other source — are ignored while the spell is in effect.'),
    'Daemonbane':       SpellClass('10', '[bWP] yard(s)', '1', 'Instant', f'You summon a blast of Hysh that passes through the border between the Realm of Chaos and the material world. The Casting Test is Opposed by the target making a Willpower Test. If you win, you obliterate a target with the Daemonic Creature Trait with a blinding white light, sending it back whence it came. If the spell successfully banishes a Daemon, everyone looking at your target, unless they possess the Arcane Magic (Light) Talent, receives +SL Blinded Conditions.'),
    'Healing Light':    SpellClass('9', '[bWP] yard(s)', '1', 'Instant', f'Your target glows with a bright, cleansing light (equivalent light to a campfire), healing Intelligence Bonus + Willpower Bonus Wounds. If the Target passes a Very Hard (–20) Endurance Test, 1 Corruption point gained in the last hour is also lost.'),
    'Net of Amyntok':   SpellClass('8', '[bINT] yard(s)', '1', 'Target’s INT Bonus round(s)', f'You cast a delicate net woven from strands of Hysh over your targets, whose minds are overcome with conundrums and puzzles, leaving them paralysed with indecision. Targets gain +1 Stunned Condition, which they cannot lose while the spell is in effect. When recovering from the Condition, targets test their Intelligence instead of the Endurance Skill. Targets with the Bestial Creature Trait are immune to this spell.'),
    'Phâ’s Protection': SpellClass('10', 'You', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'You summon a protective aura of pure, holy light. Profane creatures — those with the Undead or Daemonic Creature Trait, those with mutations, and those with more Corruption than their Willpower Bonus and Toughness Bonus combined — cannot enter the Area of Effect. Any already within the Area gain the Broken Condition until they leave. Creatures within the Area cannot gain any Corruption points while the spell is active.'),
    'Speed of Thought': SpellClass('8', 'You', 'You', '[bWP] round(s)', f'A lattice of Hysh overlays your mind, allowing you to think rapidly. Gain a bonus of +20 to Intelligence and Initiative.')
}


spells_lore_shadow = {
    'Choking Shadows':  SpellClass('6', '[bWP] yard(s)', '1', '[bWP] round(s)', f'You wrap shadowy tendrils of Ulgu around your foes’ necks. Assuming they need to breathe, they gain +1 Fatigued Condition, cannot talk, and are subject to rules for Suffocation (see page 181).'),
    'Doppelganger':     SpellClass('10', 'You', 'You', '[bINT] minute(s)', f'You weave a mask and cloak of Ulgu around your form, assuming the likeness of another humanoid creature with whom you are familiar (as determined by the GM). Your appearance will automatically fool anyone without the Second Sight Talent, though some may note if any of your mannerisms are incorrect. Those with that Talent must pass a Difficult (–10) Perception Test to notice you are disguising your form. This does not let them see through the spell. They must dispel it to do so.'),
    'Illusion':         SpellClass('8', '[WP] yard(s)', 'AoE ([bI] yard(s))', '[WP] minute(s)', f'You spin a web of intricate strands of Ulgu, obfuscating the Area of Effect with an illusory image of your choosing. You will automatically fool anyone without the Second Sight Talent. Those with that Talent must pass a Difficult (–10) Perception Test to notice the illusion. This does not let them see through the spell. They must dispel it to do so. The illusion is, by default, static. For your Action, you may make a Hard (–20) Channelling Test to make the illusion move for that Round.'),
    'Mindslip':         SpellClass('6', '1 yard', '1', '[WP] minute(s)', f'You conjure delicate threads of Ulgu in your Target’s mind, causing all prior memory of you to disappear for the spell’s duration. Once the spell is over, the Target must pass an Average (+20) Intelligence Test, or the memory loss becomes permanent until dispelled.'),
    'Mystifying Miasma':SpellClass('6', '[WP] yard(s)', 'AoE ([bWP] yard(s))', '[bWP] round(s)', f'You conjure forth a swirling mass of mist shot through with roiling shadow that flits and confounds the senses. Anyone within the mist who does not possess the Arcane Magic (Shadows) Talent is affected by the Miasma, gaining +1 Blinded, Deafened , and Fatigued Condition, which remain for the spell’s duration. Anyone affected attempting to move must pass a Challenging (+0) Perception Test, or gain the Prone Condition. If the spell is dispelled once in play, anyone affected by the spell must make a Routine (+40) Initiative Test, or gain the Stunned Condition.'),
    'Shadowsteed':      SpellClass('6', '[bWP] yard(s)', '1', 'Until the next sunrise', f'You summon forth a shadowy steed. The creature’s unnatural flesh is black as midnight, and at times it appears to be both solid and insubstantial. Use the rules for a riding horse. When the Shadowsteed is out of sunlight, it also gains the following Creature Traits: Dark Vision, Ethereal, Magical, Painless, Stealthy, Stride, Fear (1) and Ward (+9) . Even when insubstantial, Shadowsteeds may be ridden. Riders with the Arcane Magic (Shadow) Talent do so with a bonus of +20 to Ride Tests. Those without suffer a penalty of –20 to Ride Tests. Shadowsteeds are tireless, so need no rest (though their unsettled riders might!). As the first rays of dawn break over the horizon the steeds melt into insubstantial mist. If still being ridden when the spell ends, or when dispelled, the rider will suffer Falling Damage (see page 166).'),
    'Shadowstep':       SpellClass('8', '[WP] yard(s)', 'You', 'Instant', f'You create a shadowy portal of Ulgu through the aethyr. You disappear from your current location and immediately appear up to your [WP] yard(s) away. Any enemies Engaged by you on your disappearance or reappearance gain the Surprised Condition.'),
    'Shroud of Invisibility': SpellClass('8', 'Touch', '1', '[bWP] round(s)', f'You wrap the target in a shroud of Ulgu. The Target becomes invisible and cannot be perceived by mundane senses. The spell will automatically fool anyone without the Second Sight Talent. Those with the Talent must pass a Challenging (+0) Perception Test to notice that someone is nearby, though they will not be able to pin down the precise location. They must dispel the Shroud of Invisibility to do so . You are still perceptible to the other senses, and the spell will come to an end if you bring attention to yourself by making large noises or attacking someone.')
}


spells_lore_hedgecraft = {
    'Goodwill':         SpellClass('0', 'You', 'AoE ([bFEL] yard(s))', '[bWP] round(s)', f'You create an atmosphere conducive to friendliness and good spirits. All Fellowship Tests within the Area of Effect receive a bonus of +10, and Animosity and Hatred Psychologies have no effect.'),
    'Mirkride':         SpellClass('0', 'You', 'You', '[bWP] minute(s)', f'Speaking ancient words of magic, your spirit leaves your body, stepping into the Hedge, the dark space between the material world and the spirit realm. For the duration, your stand apart from the world, able to witness it invisibly, but not affect it in any way. Physical barriers are no impediment to you, and you may walk through non-magical obstacles at will. Your body remains in place, immobile and insensate. At the end of the spell you will be pulled suddenly back to your body. If your body is killed while you are walking the Hedge, your spirit will wander aimlessly for eternity.'),
    'Nepenthe':         SpellClass('0', 'Touch', 'Special', '[bWP] round(s)', f'You mutter words of power over a premade potion of herbs, magically transforming it into a potent philtre. If drunk while the spell is in effect, the target may choose to completely forget one individual, permanently.'),
    'Nostrum':          SpellClass('0', 'Touch', 'Special', '[bWP] round(s)', f'You incant a spell over an already prepared draught, imbuing it with magical power. If drunk while the spell is in effect, the target immediately heals your Willpower Bonus in Wounds and is cured of one disease. For every +2 SL you may cure an extra disease.'),
    'Part the Branches':SpellClass('0', 'You', 'You', '[WP] minute(s)', f'Your pupils dilate as you complete your incantation, and you are able to see into the Spirit world. This allows you to perceive invisible creatures, spirits, and Daemons, even those marked as impossible to see.'),
    'Protective Charm': SpellClass('0', 'Touch', 'Special', '[bWP] day(s)', f'You imbue a protective charm with a spell of protection. Those bearing the charm gain the Magic Resistance Talent. If they already have that Talent, the charm does nothing more.')
}


spells_lore_witchcraft = {
    'Blight':           SpellClass('14', '[bWP] yard(s)', 'Special', 'Special', f'You may target either a well, a field, or a domestic animal. If you successfully cast the spell, the target suffers from a blight: • A blighted well becomes instantly brackish and stagnant • Any crops currently planted in a Blighted field rot overnight • A blighted animal sickens. The afflicted beast no longer produces anything (cows produce no milk, hens produce no eggs, coats and hides grow mangy and unusable) and will die in 10–SL days'),
    'Creeping Menace':  SpellClass('6', '[WP] yard(s)', '1', '[bWP] round(s)', f'You summon a swarm of creeping, slithering creatures to harass your foes. Each target affected is immediately engaged by a swarm of Giant Rats, Giant Spiders, or Snakes. Use the standard profiles for the relevant creature type, adding the Swarm Trait. For your Action you may make a Challenging (+0) Charm Animal Test to direct 1 or more swarms to attack a different target. When the spell ends, any remaining swarms disappear into the shadows.'),
    'Curse of Crippling Pain': SpellClass('10', '[WP] yard(s)', '1', '[bWP] round(s)', f'Stabbing a crude representation of your target — a doll or puppet — you inflict crippling pain. When successfully cast, choose which hit location to stab: • Leg – Leg becomes useless, as if it was Amputated (see page 180). If running, the target also gains the Prone Condition and takes falling Damage. • Arm – Arm becomes useless, as if it was Amputated (see page 180). If target was holding anything in that hand, it is automatically dropped. • Body – Target doubles up in agony, gaining +1 Fatigued Condition, and must pass a Hard (–20) Endurance Test or gain the Prone Condition. • Head – Target gains the Stunned Condition, and must pass an Average (+20) Endurance Test or gain the Unconscious Condition for the Duration. While the spell is in effect, for your Action you may make a Channelling Test, stabbing the doll again, to affect a different location.'),
    'Curse of Ill-Fortune': SpellClass('8', '[bWP] mile(s)', '1', '[bWP] day(s)', f'The ingredient for this spell is something belonging to the target, either a personal possession or a strand of hair. For the duration, your target suffers bad luck. Laces snap, chairs break, and other minor narrative effects inconvenience them. The target suffers a penalty of –10 to all Tests, in addition to any other modifiers, and may not spend Fortune points.'),
    'Haunting Horror':  SpellClass('8', 'Touch', 'Aoe (single location)', '[WP] day(s)', f'You target a single location, such as a house or clearing, and inflict haunting dreams and waking nightmares on any who enter there. Those entering while the spell is in effect are unnerved by eerie sensations, flitting shadows, and whispered voices lurking on the threshold of hearing. Unless they possess the Arcane Magic (Witchcraft) Talent, they gain +1 Fatigued Condition. Then, unless they pass an Average (+0) Cool Test, they gain another +1 Fatigued Condition and the Broken Condition, both of which are only removed upon leaving the location.'),
    'The Evil Eye':     SpellClass('6', '[WP] yard(s)', 'Special', 'Instant', f'You lock eyes with a single target, who must be looking at you. Perform an Opposed Intimidate/Cool Test, adding any SL from your casting roll to your result. Your opponent gains 1 Fatigued Condition per +2 SL by which you win. If you win by 6+ SL, your opponent gains the Broken Condition.')
}


spells_lore_all = {
    'Beasts': spells_lore_beasts,
    "Death": spells_lore_death,
    "Fire": spells_lore_fire,
    "Heavens": spells_lore_heavens,
    "Metal": spells_lore_metal,
    "Life": spells_lore_life,
    "Light": spells_lore_light,
    "Shadow": spells_lore_shadow,
    "Hedgecraft": spells_lore_hedgecraft,
    "Witchcraft": spells_lore_witchcraft
}
